/**
 * TypeScript types for annextube data models
 *
 * Based on: annextube/schema/models.json
 *
 * Note: Manually defined for now. Future: auto-generate from schema.
 */

export interface Channel {
  channel_id: string;
  name: string;
  description?: string;
  custom_url?: string;
  subscriber_count: number;
  video_count: number;
  avatar_url: string;
  banner_url?: string;
  country?: string;
  videos: string[];
  playlists: string[];
  last_sync: string; // ISO 8601 datetime
  created_at: string; // ISO 8601 datetime
  fetched_at: string; // ISO 8601 datetime
}

export interface Video {
  video_id: string;
  title: string;
  description?: string;
  channel_id: string;
  channel_name: string;
  published_at: string; // ISO 8601 datetime
  duration: number; // seconds
  view_count: number;
  like_count: number;
  comment_count: number;
  thumbnail_url: string;
  license: 'standard' | 'creativeCommon';
  privacy_status: 'public' | 'unlisted' | 'private';
  availability: 'public' | 'private' | 'deleted' | 'unavailable';
  tags: string[];
  categories: string[];
  language?: string;
  captions_available: string[];
  has_auto_captions: boolean;
  file_path?: string;
  file_size?: number;
  download_status: 'not_downloaded' | 'tracked' | 'downloaded' | 'failed';
  source_url: string;
  fetched_at: string; // ISO 8601 datetime
  updated_at: string; // ISO 8601 datetime
}

export interface Playlist {
  playlist_id: string;
  title: string;
  description?: string;
  channel_id: string;
  channel_name: string;
  video_ids: string[];
  video_count: number;
  total_duration: number; // seconds
  privacy_status: 'public' | 'unlisted' | 'private';
  created_at: string; // ISO 8601 datetime
  updated_at: string; // ISO 8601 datetime
  last_sync: string; // ISO 8601 datetime
  fetched_at: string; // ISO 8601 datetime
}

export interface Caption {
  video_id: string;
  language_code: string; // ISO 639-1
  language_name: string;
  auto_generated: boolean;
  format: 'vtt' | 'srt';
  file_path: string;
  fetched_at: string; // ISO 8601 datetime
  updated_at: string; // ISO 8601 datetime
}

export interface Comment {
  comment_id: string;
  video_id: string;
  author: string;
  author_channel_id: string;
  author_thumbnail?: string;
  text: string;
  timestamp: string; // ISO 8601 datetime
  like_count: number;
  parent_id?: string; // For threaded replies
  reply_count: number;
  replies?: Comment[]; // Nested replies (recursive)
  fetched_at: string; // ISO 8601 datetime
}

export interface SyncState {
  source_url: string;
  source_type: 'channel' | 'playlist';
  source_id: string;
  last_sync: string; // ISO 8601 datetime
  last_video_id?: string;
  last_video_published?: string; // ISO 8601 datetime
  error_count: number;
  last_error?: string;
  next_retry?: string; // ISO 8601 datetime
  status: 'active' | 'error' | 'paused';
  videos_tracked: number;
  videos_downloaded: number;
}

export interface FilterConfig {
  name: string;
  date_range?: {
    start?: string; // ISO 8601 datetime
    end?: string; // ISO 8601 datetime
  };
  license_types?: ('standard' | 'creativeCommon')[];
  playlists?: {
    include?: string[];
    exclude?: string[];
  };
  metadata_filters?: {
    min_duration?: number;
    max_duration?: number;
    min_views?: number;
    tags?: string[];
  };
  components: {
    videos: boolean;
    metadata: boolean;
    comments: boolean;
    captions: boolean;
    thumbnails: boolean;
  };
}

/**
 * TSV row types (from videos.tsv, playlists.tsv, etc.)
 * These are flat representations with all string fields
 */
export interface VideoTSVRow {
  video_id: string;
  title: string;
  channel_id: string;
  channel_name: string;
  published_at: string;
  duration: string; // number as string
  view_count: string; // number as string
  like_count: string; // number as string
  comment_count: string; // number as string
  thumbnail_url: string;
  download_status: string;
  source_url: string;
}

export interface PlaylistTSVRow {
  playlist_id: string;
  title: string;
  channel_id: string;
  channel_name: string;
  video_count: string; // number as string
  total_duration: string; // number as string
  privacy_status: string;
  created_at: string;
  last_sync: string;
}

/**
 * Archive metadata (generated by backend)
 */
export interface ArchiveMetadata {
  version: string;
  created_at: string;
  total_videos: number;
  total_playlists: number;
  total_channels: number;
  total_size_bytes: number;
}
