#!/usr/bin/env node
/**
 * Generate TypeScript types from JSON Schema
 *
 * Reads: ../annextube/schema/models.json
 * Outputs: src/types/models.ts
 */

import { compile } from 'json-schema-to-typescript';
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const schemaPath = join(__dirname, '../../annextube/schema/models.json');
const outputPath = join(__dirname, '../src/types/models.ts');

console.log('Generating TypeScript types from JSON Schema...');
console.log(`  Schema: ${schemaPath}`);
console.log(`  Output: ${outputPath}`);

// Read the schema
const schemaText = readFileSync(schemaPath, 'utf-8');
const schema = JSON.parse(schemaText);

// Extract individual definitions and compile each
const definitions = schema.definitions || {};
const modelNames = Object.keys(definitions);

console.log(`  Found ${modelNames.length} model definitions:`, modelNames.join(', '));

const banner = `/**
 * Auto-generated TypeScript types from annextube JSON Schema
 *
 * DO NOT EDIT THIS FILE MANUALLY
 *
 * Generated from: annextube/schema/models.json
 * To regenerate: npm run generate-types
 */

`;

// Compile each definition separately
const typePromises = modelNames.map((name) => {
  const definition = definitions[name];
  // Add $id to help with naming
  definition.$id = name;

  return compile(definition, name, {
    bannerComment: '',
    style: {
      semi: true,
      singleQuote: true,
    },
    unknownAny: false,
    strictIndexSignatures: true,
    $refOptions: {
      resolve: {
        // Resolve internal refs to the definitions
        definitions: {
          order: 1,
          canRead: true,
          read(file) {
            return schema;
          },
        },
      },
    },
  });
});

Promise.all(typePromises)
  .then((typeDefinitions) => {
    // Ensure output directory exists
    mkdirSync(dirname(outputPath), { recursive: true });

    // Combine all type definitions
    const allTypes = banner + typeDefinitions.join('\n');

    // Write TypeScript definitions
    writeFileSync(outputPath, allTypes);

    console.log('✅ TypeScript types generated successfully!');
    console.log(`   Generated ${modelNames.length} interfaces`);
    console.log(`   Output: ${outputPath}`);
  })
  .catch((err) => {
    console.error('❌ Error generating types:', err);
    process.exit(1);
  });
