"""CLI entry point for annextube."""

import os
import sys
from pathlib import Path

import click

# Ensure UTF-8 encoding for Click output (fixes Unicode encoding errors)
# This must be set before any Click commands are executed
if sys.stdout.encoding != 'utf-8':
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
if sys.stderr.encoding != 'utf-8':
    import io
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')

from annextube.cli.aggregate import aggregate
from annextube.cli.backup import backup
from annextube.cli.check import check
from annextube.cli.export import export
from annextube.cli.generate_web import generate_web
from annextube.cli.info import info
from annextube.cli.init import init
from annextube.cli.init_user_config import init_user_config
from annextube.cli.serve import serve
from annextube.lib.logging_config import setup_logging

# Version - dynamically generated by setuptools-scm
try:
    from annextube._version import version as __version__
except ImportError:
    # Fallback for development without installation
    __version__ = "unknown"


@click.group()
@click.option(
    "--config",
    type=click.Path(exists=True, path_type=Path),
    help="Path to config file (default: .annextube/config.toml)",
)
@click.option(
    "--log-level",
    type=click.Choice(["info", "warning", "error", "critical", "debug", "heavy-debug"]),
    default="info",
    show_default=True,
    help="Log level (heavy-debug includes yt-dlp debug output)",
)
@click.option("--json", "json_output", is_flag=True, help="JSON output mode")
@click.option("--quiet", is_flag=True, help="Suppress console output")
@click.version_option(version=__version__, prog_name="annextube")
@click.pass_context
def cli(
    ctx: click.Context,
    config: Path | None,
    log_level: str,
    json_output: bool,
    quiet: bool,
):
    """annextube - YouTube archive system using git-annex.

    Complete channel archival with metadata, comments, captions, and incremental updates.
    """
    # Setup logging
    logger = setup_logging(
        level=log_level,
        json_format=json_output,
        quiet=quiet,
    )

    # Store context
    ctx.ensure_object(dict)
    ctx.obj["config_path"] = config
    ctx.obj["logger"] = logger
    ctx.obj["json_output"] = json_output


cli.add_command(init)
cli.add_command(init_user_config)
cli.add_command(backup)
cli.add_command(export)
cli.add_command(aggregate)
cli.add_command(generate_web)
cli.add_command(serve)
cli.add_command(info)
cli.add_command(check)


def main():
    """Main entry point."""
    try:
        cli(obj={})
    except Exception as e:
        click.echo(f"Error: {e}", err=True)
        sys.exit(1)


if __name__ == "__main__":
    main()
